#!/bin/bash

# Project Cleanup and Optimization Script
# This script cleans up duplicate files, optimizes project structure, and performs maintenance tasks

echo "🚀 Starting project cleanup and optimization..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[i]${NC} $1"
}

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# 1. Remove duplicate files
print_info "Step 1: Removing duplicate files..."
find . -name "*NEW*" -o -name "*COMPLETE*" -o -name "*PROPER*" -o -name "*TEMPLATE*" -o -name "*BACKUP*" -o -name "*OLD*" | grep -v node_modules | grep -v .git | while read file; do
    if [[ "$file" != "./README.md" ]]; then  # Keep the main README
        rm -f "$file"
        print_status "Removed duplicate file: $file"
    fi
done

# 2. Clean temporary files
print_info "Step 2: Cleaning temporary files..."
find . -name "*.tmp" -o -name "*.bak" -o -name "*.old" -o -name "*~" -o -name ".DS_Store" -o -name "Thumbs.db" -o -name "*.log" | grep -v node_modules | grep -v .git | xargs rm -f 2>/dev/null || true

# 3. Optimize project structure by organizing components
print_info "Step 3: Organizing components..."
if [ -d "src/components" ]; then
    cd src/components

    # Create organized directories if they don't exist
    mkdir -p UI/Navigation/Utils/Widgets/

    # Move components to appropriate directories
    if [ -d "DocumentationEnhancements" ]; then
        mv DocumentationEnhancements UI/
        print_status "Moved DocumentationEnhancements to UI/ directory"
    fi

    if [ -d "UIEnhancements" ]; then
        mv UIEnhancements UI/
        print_status "Moved UIEnhancements to UI/ directory"
    fi

    # Move any auth-related components to appropriate directory
    if [ -d "Auth" ]; then
        mv Auth/ Utils/
        print_status "Moved Auth component to Utils/ directory"
    fi

    # Move any navigation-related components
    if [ -d "ChapterTools" ]; then
        mv ChapterTools/ Navigation/
        print_status "Moved ChapterTools to Navigation/ directory"
    fi

    # Move chatbot to widgets
    if [ -d "Chatbot" ]; then
        mv Chatbot/ Widgets/
        print_status "Moved Chatbot to Widgets/ directory"
    fi

    cd ../..
fi

# 4. Clean build artifacts (keeping only if needed)
print_info "Step 4: Cleaning build artifacts..."
if [ -d "build" ]; then
    print_warning "Build directory found. This will be regenerated by Docusaurus."
    # Optionally remove and rebuild later
fi

# 5. Clean cache directories
print_info "Step 5: Cleaning cache directories..."
rm -rf .docusaurus
rm -rf .cache-loader
rm -rf .specify/.cache
rm -rf .vscode/.cache

# 6. Clean temporary Python caches
print_info "Step 6: Cleaning Python cache directories..."
find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
find . -type d -name "*.pyc" -exec rm -f {} + 2>/dev/null || true
find . -type f -name "*.pyo" -exec rm -f {} + 2>/dev/null || true

# 7. Optimize node_modules (optional - can be skipped for safety)
print_info "Step 7: Checking node_modules..."
if [ -d "node_modules" ]; then
    print_status "node_modules directory exists with $(du -sh node_modules | cut -f1) size"
    print_info "Run 'npm prune' to remove unused packages if needed"
fi

# 8. Clean history files that might be redundant
print_info "Step 8: Cleaning redundant history files..."
if [ -d "history" ]; then
    # Keep important history, clean temporary files
    find history -name "*.tmp" -o -name "*.bak" -o -name "*~" | xargs rm -f 2>/dev/null || true
fi

# 9. Verify project structure
print_info "Step 9: Verifying project structure..."
if [ -d "src/components/UI" ]; then
    print_status "UI components organized in src/components/UI/"
fi

if [ -d "src/components/Navigation" ]; then
    print_status "Navigation components organized in src/components/Navigation/"
fi

if [ -d "src/components/Widgets" ]; then
    print_status "Widget components organized in src/components/Widgets/"
fi

if [ -d "src/components/Utils" ]; then
    print_status "Utility components organized in src/components/Utils/"
fi

# 10. Check for main README
if [ -f "README.md" ]; then
    print_status "Main README.md file exists and is properly structured"
else
    print_error "Main README.md file is missing!"
fi

# 11. Clean up any temporary files in the root
print_info "Step 10: Final cleanup of root directory..."
find . -maxdepth 1 -type f -name "*.tmp" -o -name "*.bak" -o -name "*~" | xargs rm -f 2>/dev/null || true

# 12. Display final project statistics
print_info "Step 11: Final project statistics:"
echo "Files in root: $(ls -1 | wc -l)"
echo "Directories in src/: $(ls -1 src/ | wc -l)"
echo "Markdown files in docs/: $(find docs -name "*.md" | wc -l)"

# 13. Regenerate Docusaurus build (optional)
print_info "Step 12: Project cleanup complete!"
echo ""
echo "Next steps you might want to take:"
echo "1. Run 'npm run build' to regenerate the documentation site"
echo "2. Run 'npm audit' to check for security vulnerabilities"
echo "3. Run 'npm run serve' to test the site locally"
echo ""
print_status "Project optimization and cleanup completed successfully! 🎉"